@baseUrl = http://localhost:3000/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGZhZGRiYjFjZjY0NzUyOWI1MWQyYzQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjE1NzYzMTgsImV4cCI6MTc2MTU3OTkxOH0.YHS99nU23GGAr-UeJKS78sTmlaCvqSoi6WtC7DFq6EQ

# ====================|| ADMIN API ||====================

### Get articles list
GET {{baseUrl}}/admin/blog/articles
Content-Type: application/json
Authorization: Bearer {{accessToken}}
###

### Create a new article
POST {{baseUrl}}/admin/blog/articles
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Published Three",
    "short_description": "this is the short description of the post: published three.",
    "body": "this is the body of the post: published three.",
    "image": "https://media.post.rvohealth.io/wp-content/uploads/2022/06/female-rubbing-sunscreen-on-skin-732-549-feature-thumb-732x549.jpg",
    "is_published": true,
    "slug": "published-three"
}

###

# ====================|| PUBLIC USERS API ||====================

### Get articles list
GET {{baseUrl}}/blog/articles
Content-Type: application/json
###


