import type { Metadata } from 'next'

import './globals.css'
import ProviderWrapper from '../components/layout/provider-wrapper'
import Footer from '@/components/footer/footer'
import ThemeModeBtn from '@/components/theme-mode-btn'
import PageWrapper from '@/components/layout/page-wrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactElement
}>) {
  return (
    <html lang="en">
      <body>
        <ProviderWrapper>
          <PageWrapper>
            {children}
            <ThemeModeBtn />
            <Footer />
          </PageWrapper>
        </ProviderWrapper>
      </body>
    </html>
  )
}
