import type { Metadata } from 'next'

import '@/styles/globals.css'
import ProviderWrapper from '@/components/layout/provider-wrapper'
import PageWrapper from '@/components/layout/page-wrapper'
import ThemeModeBtn from '@/components/theme-mode-btn'
import DashboardLayout from '@/components/dashboard/layout/dash-layout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ProviderWrapper>
          <PageWrapper>
            <DashboardLayout>
              <main className="flex-1">{children}</main>
            </DashboardLayout>
            <ThemeModeBtn />
          </PageWrapper>
        </ProviderWrapper>
      </body>
    </html>
  )
}
