import { Suspense } from 'react'
import type { Metadata } from 'next'

import '@/styles/globals.css'
import ProviderWrapper from '@/components/layout/provider-wrapper'
import PageWrapper from '@/components/layout/page-wrapper'
import DashboardLayout from '@/components/dashboard/layout/dash-layout'
import NProgressBar from '@/components/nprogress-bar/nprogress-bar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense>
          <NProgressBar />
        </Suspense>
        <ProviderWrapper>
          <PageWrapper>
            <DashboardLayout>
              <main className="flex-1">{children}</main>
            </DashboardLayout>
          </PageWrapper>
        </ProviderWrapper>
      </body>
    </html>
  )
}
