import type { Metadata } from 'next'

import '@/styles/globals.css'
import ProviderWrapper from '@/components/layout/provider-wrapper'
import Footer from '@/components/footer/footer'
import PageWrapper from '@/components/layout/page-wrapper'
import Header from '@/components/navbar/header'
import NProgressBar from '@/components/nprogress-bar/nprogress-bar'
import ThemeModeBtn from '@/components/theme-mode-btn'
import HomeTopImage from '@/components/home/top-image'
import AuthVerifier from '@/components/auth/auth-verifier'
import { Suspense } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense>
          <NProgressBar />
        </Suspense>
        <ProviderWrapper>
          <PageWrapper>
            <div className="flex min-h-screen flex-col">
              <AuthVerifier />
              <HomeTopImage />
              <Header />
              <main className="flex-1">{children}</main>
              <ThemeModeBtn fixed />
              <Footer />
            </div>
          </PageWrapper>
        </ProviderWrapper>
      </body>
    </html>
  )
}
